#!/usr/bin/bash

file_name=$1
file_type=$2

if [ -z ${file_name} ]
then
    file_name="__none__"
    file_type="__none__"
fi

if [ -n ${file_name} ] && [ -n ${file_type} ] && [ $file_type == "rs" ]
then
    rustc $file_name.rs -o $file_name.rustc
    ./$file_name.rustc
fi

if [ -n ${file_name} ] && [ -n ${file_type} ] && [ $file_type == "cpp" ]
then
    g++ $file_name.cpp -o $file_name.gpp
    ./$file_name.gpp
fi

if [ -n ${file_name} ] && [ -n ${file_type} ] && [ $file_type == "c" ]
then
    gcc $file_name.c -o $file_name.gcc
    ./$file_name.gcc
fi
